stages:
    - build-docker-image
    
build image:
    image: docker
    stage: build-docker-image
    services:
        - docker:dind
    script:
        - echo $CI_REGISTARY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_GITLAB_TOKEN --password-stdin
        - docker build -t hub-peerxp.vegaops.com/devops-assignment/java_200922_2095 .
        - docker push hub-peerxp.vegaops.com/devops-assignment/java_200922_2095 